### ISSUE TITLE
Consultas

### ISSUE THREAD

**Issue by nataliamarinn** [aid-austral-2024/tarea2-nataliamarinn#1]
Quería consultar algunas cuestiones sobre la entrega: 
1) el archivo qmd debe tener todo el código utilizado, o esto debe estar en un script.r?
2) Debe estar estructuradas las secciones? o puedo comentar la limpieza sin poner el código y mostrar el análisis de datos?
3) El "estilo de entrega" es para cualquier persona/jefe o tiene un tono más trabajo práctico?

Muchas Gracias

**Comment by DiegoNOB** [comment]
Hola Natalia! Te respondemos las consultas:

1. No es necesario que el qmd contenga todo el código que escribiste, sólo el necesario para generar el reporte que deseas entregar. Si hay bloques grandes de código que solo necesitas correr una vez al principio (por ej limpieza) y no son necesarios para el html, podes ubicarlos en scripts aparte.
2. Se espera que las secciones estén estructuradas, cuando hablas de la limpieza podés describir los pasos seguidos y linkear/referenciar el archivo donde guardes el código de limpieza.
3. El estilo de entrega puede tener un tono de TP, no es necesario que esté orientado sí o sí a un estilo "empresarial".

Saludos!

**Comment by nataliamarinn** [comment]
Muchas gracias por la respuesta!
Saludos
